#include "EyerAVPixelFormat.hpp"

#include "EyerAVFFmpegHeader.hpp"

#define EYER_EXT_CVPIXELBUFFER_ID (AV_PIX_FMT_NB+0001)

namespace Eyer
{
    EyerAVPixelFormat EyerAVPixelFormat::EYER_KEEP_SAME (-2, -2, "EYER_KEEP_SAME", "和原视频保持一致");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NONE (AV_PIX_FMT_NONE, AV_PIX_FMT_NONE, "EYER_NONE", "NONE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P (AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV420P, "EYER_YUV420P", "YUV420P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUYV422 (AV_PIX_FMT_YUYV422, AV_PIX_FMT_YUYV422, "EYER_YUYV422", "YUYV422");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB24 (AV_PIX_FMT_RGB24, AV_PIX_FMT_RGB24, "EYER_RGB24", "RGB24");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR24 (AV_PIX_FMT_BGR24, AV_PIX_FMT_BGR24, "EYER_BGR24", "BGR24");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P (AV_PIX_FMT_YUV422P, AV_PIX_FMT_YUV422P, "EYER_YUV422P", "YUV422P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P (AV_PIX_FMT_YUV444P, AV_PIX_FMT_YUV444P, "EYER_YUV444P", "YUV444P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV410P (AV_PIX_FMT_YUV410P, AV_PIX_FMT_YUV410P, "EYER_YUV410P", "YUV410P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV411P (AV_PIX_FMT_YUV411P, AV_PIX_FMT_YUV411P, "EYER_YUV411P", "YUV411P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY8 (AV_PIX_FMT_GRAY8, AV_PIX_FMT_GRAY8, "EYER_GRAY8", "GRAY8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_MONOWHITE (AV_PIX_FMT_MONOWHITE, AV_PIX_FMT_MONOWHITE, "EYER_MONOWHITE", "MONOWHITE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_MONOBLACK (AV_PIX_FMT_MONOBLACK, AV_PIX_FMT_MONOBLACK, "EYER_MONOBLACK", "MONOBLACK");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_PAL8 (AV_PIX_FMT_PAL8, AV_PIX_FMT_PAL8, "EYER_PAL8", "PAL8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVJ420P (AV_PIX_FMT_YUVJ420P, AV_PIX_FMT_YUVJ420P, "EYER_YUVJ420P", "YUVJ420P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVJ422P (AV_PIX_FMT_YUVJ422P, AV_PIX_FMT_YUVJ422P, "EYER_YUVJ422P", "YUVJ422P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVJ444P (AV_PIX_FMT_YUVJ444P, AV_PIX_FMT_YUVJ444P, "EYER_YUVJ444P", "YUVJ444P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_UYVY422 (AV_PIX_FMT_UYVY422, AV_PIX_FMT_UYVY422, "EYER_UYVY422", "UYVY422");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_UYYVYY411 (AV_PIX_FMT_UYYVYY411, AV_PIX_FMT_UYYVYY411, "EYER_UYYVYY411", "UYYVYY411");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR8 (AV_PIX_FMT_BGR8, AV_PIX_FMT_BGR8, "EYER_BGR8", "BGR8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR4 (AV_PIX_FMT_BGR4, AV_PIX_FMT_BGR4, "EYER_BGR4", "BGR4");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR4_BYTE (AV_PIX_FMT_BGR4_BYTE, AV_PIX_FMT_BGR4_BYTE, "EYER_BGR4_BYTE", "BGR4_BYTE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB8 (AV_PIX_FMT_RGB8, AV_PIX_FMT_RGB8, "EYER_RGB8", "RGB8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB4 (AV_PIX_FMT_RGB4, AV_PIX_FMT_RGB4, "EYER_RGB4", "RGB4");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB4_BYTE (AV_PIX_FMT_RGB4_BYTE, AV_PIX_FMT_RGB4_BYTE, "EYER_RGB4_BYTE", "RGB4_BYTE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV12 (AV_PIX_FMT_NV12, AV_PIX_FMT_NV12, "EYER_NV12", "NV12");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV21 (AV_PIX_FMT_NV21, AV_PIX_FMT_NV21, "EYER_NV21", "NV21");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_ARGB (AV_PIX_FMT_ARGB, AV_PIX_FMT_ARGB, "EYER_ARGB", "ARGB");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGBA (AV_PIX_FMT_RGBA, AV_PIX_FMT_RGBA, "EYER_RGBA", "RGBA");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_ABGR (AV_PIX_FMT_ABGR, AV_PIX_FMT_ABGR, "EYER_ABGR", "ABGR");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGRA (AV_PIX_FMT_BGRA, AV_PIX_FMT_BGRA, "EYER_BGRA", "BGRA");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY16BE (AV_PIX_FMT_GRAY16BE, AV_PIX_FMT_GRAY16BE, "EYER_GRAY16BE", "GRAY16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY16LE (AV_PIX_FMT_GRAY16LE, AV_PIX_FMT_GRAY16LE, "EYER_GRAY16LE", "GRAY16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV440P (AV_PIX_FMT_YUV440P, AV_PIX_FMT_YUV440P, "EYER_YUV440P", "YUV440P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVJ440P (AV_PIX_FMT_YUVJ440P, AV_PIX_FMT_YUVJ440P, "EYER_YUVJ440P", "YUVJ440P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P (AV_PIX_FMT_YUVA420P, AV_PIX_FMT_YUVA420P, "EYER_YUVA420P", "YUVA420P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB48BE (AV_PIX_FMT_RGB48BE, AV_PIX_FMT_RGB48BE, "EYER_RGB48BE", "RGB48BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB48LE (AV_PIX_FMT_RGB48LE, AV_PIX_FMT_RGB48LE, "EYER_RGB48LE", "RGB48LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB565BE (AV_PIX_FMT_RGB565BE, AV_PIX_FMT_RGB565BE, "EYER_RGB565BE", "RGB565BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB565LE (AV_PIX_FMT_RGB565LE, AV_PIX_FMT_RGB565LE, "EYER_RGB565LE", "RGB565LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB555BE (AV_PIX_FMT_RGB555BE, AV_PIX_FMT_RGB555BE, "EYER_RGB555BE", "RGB555BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB555LE (AV_PIX_FMT_RGB555LE, AV_PIX_FMT_RGB555LE, "EYER_RGB555LE", "RGB555LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR565BE (AV_PIX_FMT_BGR565BE, AV_PIX_FMT_BGR565BE, "EYER_BGR565BE", "BGR565BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR565LE (AV_PIX_FMT_BGR565LE, AV_PIX_FMT_BGR565LE, "EYER_BGR565LE", "BGR565LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR555BE (AV_PIX_FMT_BGR555BE, AV_PIX_FMT_BGR555BE, "EYER_BGR555BE", "BGR555BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR555LE (AV_PIX_FMT_BGR555LE, AV_PIX_FMT_BGR555LE, "EYER_BGR555LE", "BGR555LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P16LE (AV_PIX_FMT_YUV420P16LE, AV_PIX_FMT_YUV420P16LE, "EYER_YUV420P16LE", "YUV420P16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P16BE (AV_PIX_FMT_YUV420P16BE, AV_PIX_FMT_YUV420P16BE, "EYER_YUV420P16BE", "YUV420P16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P16LE (AV_PIX_FMT_YUV422P16LE, AV_PIX_FMT_YUV422P16LE, "EYER_YUV422P16LE", "YUV422P16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P16BE (AV_PIX_FMT_YUV422P16BE, AV_PIX_FMT_YUV422P16BE, "EYER_YUV422P16BE", "YUV422P16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P16LE (AV_PIX_FMT_YUV444P16LE, AV_PIX_FMT_YUV444P16LE, "EYER_YUV444P16LE", "YUV444P16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P16BE (AV_PIX_FMT_YUV444P16BE, AV_PIX_FMT_YUV444P16BE, "EYER_YUV444P16BE", "YUV444P16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB444LE (AV_PIX_FMT_RGB444LE, AV_PIX_FMT_RGB444LE, "EYER_RGB444LE", "RGB444LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB444BE (AV_PIX_FMT_RGB444BE, AV_PIX_FMT_RGB444BE, "EYER_RGB444BE", "RGB444BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR444LE (AV_PIX_FMT_BGR444LE, AV_PIX_FMT_BGR444LE, "EYER_BGR444LE", "BGR444LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR444BE (AV_PIX_FMT_BGR444BE, AV_PIX_FMT_BGR444BE, "EYER_BGR444BE", "BGR444BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YA8 (AV_PIX_FMT_YA8, AV_PIX_FMT_YA8, "EYER_YA8", "YA8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR48BE (AV_PIX_FMT_BGR48BE, AV_PIX_FMT_BGR48BE, "EYER_BGR48BE", "BGR48BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR48LE (AV_PIX_FMT_BGR48LE, AV_PIX_FMT_BGR48LE, "EYER_BGR48LE", "BGR48LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P9BE (AV_PIX_FMT_YUV420P9BE, AV_PIX_FMT_YUV420P9BE, "EYER_YUV420P9BE", "YUV420P9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P9LE (AV_PIX_FMT_YUV420P9LE, AV_PIX_FMT_YUV420P9LE, "EYER_YUV420P9LE", "YUV420P9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P10BE (AV_PIX_FMT_YUV420P10BE, AV_PIX_FMT_YUV420P10BE, "EYER_YUV420P10BE", "YUV420P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P10LE (AV_PIX_FMT_YUV420P10LE, AV_PIX_FMT_YUV420P10LE, "EYER_YUV420P10LE", "YUV420P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P10BE (AV_PIX_FMT_YUV422P10BE, AV_PIX_FMT_YUV422P10BE, "EYER_YUV422P10BE", "YUV422P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P10LE (AV_PIX_FMT_YUV422P10LE, AV_PIX_FMT_YUV422P10LE, "EYER_YUV422P10LE", "YUV422P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P9BE (AV_PIX_FMT_YUV444P9BE, AV_PIX_FMT_YUV444P9BE, "EYER_YUV444P9BE", "YUV444P9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P9LE (AV_PIX_FMT_YUV444P9LE, AV_PIX_FMT_YUV444P9LE, "EYER_YUV444P9LE", "YUV444P9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P10BE (AV_PIX_FMT_YUV444P10BE, AV_PIX_FMT_YUV444P10BE, "EYER_YUV444P10BE", "YUV444P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P10LE (AV_PIX_FMT_YUV444P10LE, AV_PIX_FMT_YUV444P10LE, "EYER_YUV444P10LE", "YUV444P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P9BE (AV_PIX_FMT_YUV422P9BE, AV_PIX_FMT_YUV422P9BE, "EYER_YUV422P9BE", "YUV422P9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P9LE (AV_PIX_FMT_YUV422P9LE, AV_PIX_FMT_YUV422P9LE, "EYER_YUV422P9LE", "YUV422P9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP (AV_PIX_FMT_GBRP, AV_PIX_FMT_GBRP, "EYER_GBRP", "GBRP");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP9BE (AV_PIX_FMT_GBRP9BE, AV_PIX_FMT_GBRP9BE, "EYER_GBRP9BE", "GBRP9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP9LE (AV_PIX_FMT_GBRP9LE, AV_PIX_FMT_GBRP9LE, "EYER_GBRP9LE", "GBRP9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP10BE (AV_PIX_FMT_GBRP10BE, AV_PIX_FMT_GBRP10BE, "EYER_GBRP10BE", "GBRP10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP10LE (AV_PIX_FMT_GBRP10LE, AV_PIX_FMT_GBRP10LE, "EYER_GBRP10LE", "GBRP10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP16BE (AV_PIX_FMT_GBRP16BE, AV_PIX_FMT_GBRP16BE, "EYER_GBRP16BE", "GBRP16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP16LE (AV_PIX_FMT_GBRP16LE, AV_PIX_FMT_GBRP16LE, "EYER_GBRP16LE", "GBRP16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P (AV_PIX_FMT_YUVA422P, AV_PIX_FMT_YUVA422P, "EYER_YUVA422P", "YUVA422P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P (AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUVA444P, "EYER_YUVA444P", "YUVA444P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P9BE (AV_PIX_FMT_YUVA420P9BE, AV_PIX_FMT_YUVA420P9BE, "EYER_YUVA420P9BE", "YUVA420P9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P9LE (AV_PIX_FMT_YUVA420P9LE, AV_PIX_FMT_YUVA420P9LE, "EYER_YUVA420P9LE", "YUVA420P9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P9BE (AV_PIX_FMT_YUVA422P9BE, AV_PIX_FMT_YUVA422P9BE, "EYER_YUVA422P9BE", "YUVA422P9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P9LE (AV_PIX_FMT_YUVA422P9LE, AV_PIX_FMT_YUVA422P9LE, "EYER_YUVA422P9LE", "YUVA422P9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P9BE (AV_PIX_FMT_YUVA444P9BE, AV_PIX_FMT_YUVA444P9BE, "EYER_YUVA444P9BE", "YUVA444P9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P9LE (AV_PIX_FMT_YUVA444P9LE, AV_PIX_FMT_YUVA444P9LE, "EYER_YUVA444P9LE", "YUVA444P9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P10BE (AV_PIX_FMT_YUVA420P10BE, AV_PIX_FMT_YUVA420P10BE, "EYER_YUVA420P10BE", "YUVA420P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P10LE (AV_PIX_FMT_YUVA420P10LE, AV_PIX_FMT_YUVA420P10LE, "EYER_YUVA420P10LE", "YUVA420P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P10BE (AV_PIX_FMT_YUVA422P10BE, AV_PIX_FMT_YUVA422P10BE, "EYER_YUVA422P10BE", "YUVA422P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P10LE (AV_PIX_FMT_YUVA422P10LE, AV_PIX_FMT_YUVA422P10LE, "EYER_YUVA422P10LE", "YUVA422P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P10BE (AV_PIX_FMT_YUVA444P10BE, AV_PIX_FMT_YUVA444P10BE, "EYER_YUVA444P10BE", "YUVA444P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P10LE (AV_PIX_FMT_YUVA444P10LE, AV_PIX_FMT_YUVA444P10LE, "EYER_YUVA444P10LE", "YUVA444P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P16BE (AV_PIX_FMT_YUVA420P16BE, AV_PIX_FMT_YUVA420P16BE, "EYER_YUVA420P16BE", "YUVA420P16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA420P16LE (AV_PIX_FMT_YUVA420P16LE, AV_PIX_FMT_YUVA420P16LE, "EYER_YUVA420P16LE", "YUVA420P16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P16BE (AV_PIX_FMT_YUVA422P16BE, AV_PIX_FMT_YUVA422P16BE, "EYER_YUVA422P16BE", "YUVA422P16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P16LE (AV_PIX_FMT_YUVA422P16LE, AV_PIX_FMT_YUVA422P16LE, "EYER_YUVA422P16LE", "YUVA422P16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P16BE (AV_PIX_FMT_YUVA444P16BE, AV_PIX_FMT_YUVA444P16BE, "EYER_YUVA444P16BE", "YUVA444P16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P16LE (AV_PIX_FMT_YUVA444P16LE, AV_PIX_FMT_YUVA444P16LE, "EYER_YUVA444P16LE", "YUVA444P16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_XYZ12LE (AV_PIX_FMT_XYZ12LE, AV_PIX_FMT_XYZ12LE, "EYER_XYZ12LE", "XYZ12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_XYZ12BE (AV_PIX_FMT_XYZ12BE, AV_PIX_FMT_XYZ12BE, "EYER_XYZ12BE", "XYZ12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV16 (AV_PIX_FMT_NV16, AV_PIX_FMT_NV16, "EYER_NV16", "NV16");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV20LE (AV_PIX_FMT_NV20LE, AV_PIX_FMT_NV20LE, "EYER_NV20LE", "NV20LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV20BE (AV_PIX_FMT_NV20BE, AV_PIX_FMT_NV20BE, "EYER_NV20BE", "NV20BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGBA64BE (AV_PIX_FMT_RGBA64BE, AV_PIX_FMT_RGBA64BE, "EYER_RGBA64BE", "RGBA64BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGBA64LE (AV_PIX_FMT_RGBA64LE, AV_PIX_FMT_RGBA64LE, "EYER_RGBA64LE", "RGBA64LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGRA64BE (AV_PIX_FMT_BGRA64BE, AV_PIX_FMT_BGRA64BE, "EYER_BGRA64BE", "BGRA64BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGRA64LE (AV_PIX_FMT_BGRA64LE, AV_PIX_FMT_BGRA64LE, "EYER_BGRA64LE", "BGRA64LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YVYU422 (AV_PIX_FMT_YVYU422, AV_PIX_FMT_YVYU422, "EYER_YVYU422", "YVYU422");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YA16BE (AV_PIX_FMT_YA16BE, AV_PIX_FMT_YA16BE, "EYER_YA16BE", "YA16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YA16LE (AV_PIX_FMT_YA16LE, AV_PIX_FMT_YA16LE, "EYER_YA16LE", "YA16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP (AV_PIX_FMT_GBRAP, AV_PIX_FMT_GBRAP, "EYER_GBRAP", "GBRAP");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP16BE (AV_PIX_FMT_GBRAP16BE, AV_PIX_FMT_GBRAP16BE, "EYER_GBRAP16BE", "GBRAP16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP16LE (AV_PIX_FMT_GBRAP16LE, AV_PIX_FMT_GBRAP16LE, "EYER_GBRAP16LE", "GBRAP16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_0RGB (AV_PIX_FMT_0RGB, AV_PIX_FMT_0RGB, "EYER_0RGB", "0RGB");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_RGB0 (AV_PIX_FMT_RGB0, AV_PIX_FMT_RGB0, "EYER_RGB0", "RGB0");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_0BGR (AV_PIX_FMT_0BGR, AV_PIX_FMT_0BGR, "EYER_0BGR", "0BGR");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BGR0 (AV_PIX_FMT_BGR0, AV_PIX_FMT_BGR0, "EYER_BGR0", "BGR0");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P12BE (AV_PIX_FMT_YUV420P12BE, AV_PIX_FMT_YUV420P12BE, "EYER_YUV420P12BE", "YUV420P12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P12LE (AV_PIX_FMT_YUV420P12LE, AV_PIX_FMT_YUV420P12LE, "EYER_YUV420P12LE", "YUV420P12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P14BE (AV_PIX_FMT_YUV420P14BE, AV_PIX_FMT_YUV420P14BE, "EYER_YUV420P14BE", "YUV420P14BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV420P14LE (AV_PIX_FMT_YUV420P14LE, AV_PIX_FMT_YUV420P14LE, "EYER_YUV420P14LE", "YUV420P14LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P12BE (AV_PIX_FMT_YUV422P12BE, AV_PIX_FMT_YUV422P12BE, "EYER_YUV422P12BE", "YUV422P12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P12LE (AV_PIX_FMT_YUV422P12LE, AV_PIX_FMT_YUV422P12LE, "EYER_YUV422P12LE", "YUV422P12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P14BE (AV_PIX_FMT_YUV422P14BE, AV_PIX_FMT_YUV422P14BE, "EYER_YUV422P14BE", "YUV422P14BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV422P14LE (AV_PIX_FMT_YUV422P14LE, AV_PIX_FMT_YUV422P14LE, "EYER_YUV422P14LE", "YUV422P14LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P12BE (AV_PIX_FMT_YUV444P12BE, AV_PIX_FMT_YUV444P12BE, "EYER_YUV444P12BE", "YUV444P12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P12LE (AV_PIX_FMT_YUV444P12LE, AV_PIX_FMT_YUV444P12LE, "EYER_YUV444P12LE", "YUV444P12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P14BE (AV_PIX_FMT_YUV444P14BE, AV_PIX_FMT_YUV444P14BE, "EYER_YUV444P14BE", "YUV444P14BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV444P14LE (AV_PIX_FMT_YUV444P14LE, AV_PIX_FMT_YUV444P14LE, "EYER_YUV444P14LE", "YUV444P14LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP12BE (AV_PIX_FMT_GBRP12BE, AV_PIX_FMT_GBRP12BE, "EYER_GBRP12BE", "GBRP12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP12LE (AV_PIX_FMT_GBRP12LE, AV_PIX_FMT_GBRP12LE, "EYER_GBRP12LE", "GBRP12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP14BE (AV_PIX_FMT_GBRP14BE, AV_PIX_FMT_GBRP14BE, "EYER_GBRP14BE", "GBRP14BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRP14LE (AV_PIX_FMT_GBRP14LE, AV_PIX_FMT_GBRP14LE, "EYER_GBRP14LE", "GBRP14LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVJ411P (AV_PIX_FMT_YUVJ411P, AV_PIX_FMT_YUVJ411P, "EYER_YUVJ411P", "YUVJ411P");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_BGGR8 (AV_PIX_FMT_BAYER_BGGR8, AV_PIX_FMT_BAYER_BGGR8, "EYER_BAYER_BGGR8", "BAYER_BGGR8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_RGGB8 (AV_PIX_FMT_BAYER_RGGB8, AV_PIX_FMT_BAYER_RGGB8, "EYER_BAYER_RGGB8", "BAYER_RGGB8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_GBRG8 (AV_PIX_FMT_BAYER_GBRG8, AV_PIX_FMT_BAYER_GBRG8, "EYER_BAYER_GBRG8", "BAYER_GBRG8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_GRBG8 (AV_PIX_FMT_BAYER_GRBG8, AV_PIX_FMT_BAYER_GRBG8, "EYER_BAYER_GRBG8", "BAYER_GRBG8");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_BGGR16LE (AV_PIX_FMT_BAYER_BGGR16LE, AV_PIX_FMT_BAYER_BGGR16LE, "EYER_BAYER_BGGR16LE", "BAYER_BGGR16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_BGGR16BE (AV_PIX_FMT_BAYER_BGGR16BE, AV_PIX_FMT_BAYER_BGGR16BE, "EYER_BAYER_BGGR16BE", "BAYER_BGGR16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_RGGB16LE (AV_PIX_FMT_BAYER_RGGB16LE, AV_PIX_FMT_BAYER_RGGB16LE, "EYER_BAYER_RGGB16LE", "BAYER_RGGB16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_RGGB16BE (AV_PIX_FMT_BAYER_RGGB16BE, AV_PIX_FMT_BAYER_RGGB16BE, "EYER_BAYER_RGGB16BE", "BAYER_RGGB16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_GBRG16LE (AV_PIX_FMT_BAYER_GBRG16LE, AV_PIX_FMT_BAYER_GBRG16LE, "EYER_BAYER_GBRG16LE", "BAYER_GBRG16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_GBRG16BE (AV_PIX_FMT_BAYER_GBRG16BE, AV_PIX_FMT_BAYER_GBRG16BE, "EYER_BAYER_GBRG16BE", "BAYER_GBRG16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_GRBG16LE (AV_PIX_FMT_BAYER_GRBG16LE, AV_PIX_FMT_BAYER_GRBG16LE, "EYER_BAYER_GRBG16LE", "BAYER_GRBG16LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_BAYER_GRBG16BE (AV_PIX_FMT_BAYER_GRBG16BE, AV_PIX_FMT_BAYER_GRBG16BE, "EYER_BAYER_GRBG16BE", "BAYER_GRBG16BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV440P10LE (AV_PIX_FMT_YUV440P10LE, AV_PIX_FMT_YUV440P10LE, "EYER_YUV440P10LE", "YUV440P10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV440P10BE (AV_PIX_FMT_YUV440P10BE, AV_PIX_FMT_YUV440P10BE, "EYER_YUV440P10BE", "YUV440P10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV440P12LE (AV_PIX_FMT_YUV440P12LE, AV_PIX_FMT_YUV440P12LE, "EYER_YUV440P12LE", "YUV440P12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUV440P12BE (AV_PIX_FMT_YUV440P12BE, AV_PIX_FMT_YUV440P12BE, "EYER_YUV440P12BE", "YUV440P12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_AYUV64LE (AV_PIX_FMT_AYUV64LE, AV_PIX_FMT_AYUV64LE, "EYER_AYUV64LE", "AYUV64LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_AYUV64BE (AV_PIX_FMT_AYUV64BE, AV_PIX_FMT_AYUV64BE, "EYER_AYUV64BE", "AYUV64BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_P010LE (AV_PIX_FMT_P010LE, AV_PIX_FMT_P010LE, "EYER_P010LE", "P010LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_P010BE (AV_PIX_FMT_P010BE, AV_PIX_FMT_P010BE, "EYER_P010BE", "P010BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP12BE (AV_PIX_FMT_GBRAP12BE, AV_PIX_FMT_GBRAP12BE, "EYER_GBRAP12BE", "GBRAP12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP12LE (AV_PIX_FMT_GBRAP12LE, AV_PIX_FMT_GBRAP12LE, "EYER_GBRAP12LE", "GBRAP12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP10BE (AV_PIX_FMT_GBRAP10BE, AV_PIX_FMT_GBRAP10BE, "EYER_GBRAP10BE", "GBRAP10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAP10LE (AV_PIX_FMT_GBRAP10LE, AV_PIX_FMT_GBRAP10LE, "EYER_GBRAP10LE", "GBRAP10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY12BE (AV_PIX_FMT_GRAY12BE, AV_PIX_FMT_GRAY12BE, "EYER_GRAY12BE", "GRAY12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY12LE (AV_PIX_FMT_GRAY12LE, AV_PIX_FMT_GRAY12LE, "EYER_GRAY12LE", "GRAY12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY10BE (AV_PIX_FMT_GRAY10BE, AV_PIX_FMT_GRAY10BE, "EYER_GRAY10BE", "GRAY10BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY10LE (AV_PIX_FMT_GRAY10LE, AV_PIX_FMT_GRAY10LE, "EYER_GRAY10LE", "GRAY10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_P016LE (AV_PIX_FMT_P016LE, AV_PIX_FMT_P016LE, "EYER_P016LE", "P016LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_P016BE (AV_PIX_FMT_P016BE, AV_PIX_FMT_P016BE, "EYER_P016BE", "P016BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY9BE (AV_PIX_FMT_GRAY9BE, AV_PIX_FMT_GRAY9BE, "EYER_GRAY9BE", "GRAY9BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY9LE (AV_PIX_FMT_GRAY9LE, AV_PIX_FMT_GRAY9LE, "EYER_GRAY9LE", "GRAY9LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRPF32BE (AV_PIX_FMT_GBRPF32BE, AV_PIX_FMT_GBRPF32BE, "EYER_GBRPF32BE", "GBRPF32BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRPF32LE (AV_PIX_FMT_GBRPF32LE, AV_PIX_FMT_GBRPF32LE, "EYER_GBRPF32LE", "GBRPF32LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAPF32BE (AV_PIX_FMT_GBRAPF32BE, AV_PIX_FMT_GBRAPF32BE, "EYER_GBRAPF32BE", "GBRAPF32BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GBRAPF32LE (AV_PIX_FMT_GBRAPF32LE, AV_PIX_FMT_GBRAPF32LE, "EYER_GBRAPF32LE", "GBRAPF32LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY14BE (AV_PIX_FMT_GRAY14BE, AV_PIX_FMT_GRAY14BE, "EYER_GRAY14BE", "GRAY14BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAY14LE (AV_PIX_FMT_GRAY14LE, AV_PIX_FMT_GRAY14LE, "EYER_GRAY14LE", "GRAY14LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAYF32BE (AV_PIX_FMT_GRAYF32BE, AV_PIX_FMT_GRAYF32BE, "EYER_GRAYF32BE", "GRAYF32BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_GRAYF32LE (AV_PIX_FMT_GRAYF32LE, AV_PIX_FMT_GRAYF32LE, "EYER_GRAYF32LE", "GRAYF32LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P12BE (AV_PIX_FMT_YUVA422P12BE, AV_PIX_FMT_YUVA422P12BE, "EYER_YUVA422P12BE", "YUVA422P12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA422P12LE (AV_PIX_FMT_YUVA422P12LE, AV_PIX_FMT_YUVA422P12LE, "EYER_YUVA422P12LE", "YUVA422P12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P12BE (AV_PIX_FMT_YUVA444P12BE, AV_PIX_FMT_YUVA444P12BE, "EYER_YUVA444P12BE", "YUVA444P12BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_YUVA444P12LE (AV_PIX_FMT_YUVA444P12LE, AV_PIX_FMT_YUVA444P12LE, "EYER_YUVA444P12LE", "YUVA444P12LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV24 (AV_PIX_FMT_NV24, AV_PIX_FMT_NV24, "EYER_NV24", "NV24");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_NV42 (AV_PIX_FMT_NV42, AV_PIX_FMT_NV42, "EYER_NV42", "NV42");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_Y210BE (AV_PIX_FMT_Y210BE, AV_PIX_FMT_Y210BE, "EYER_Y210BE", "Y210BE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_Y210LE (AV_PIX_FMT_Y210LE, AV_PIX_FMT_Y210LE, "EYER_Y210LE", "Y210LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_X2RGB10LE (AV_PIX_FMT_X2RGB10LE, AV_PIX_FMT_X2RGB10LE, "EYER_X2RGB10LE", "X2RGB10LE");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_X2RGB10BE (AV_PIX_FMT_X2RGB10BE, AV_PIX_FMT_X2RGB10BE, "EYER_X2RGB10BE", "X2RGB10BE");


    EyerAVPixelFormat EyerAVPixelFormat::EYER_D3D11 (AV_PIX_FMT_D3D11, AV_PIX_FMT_D3D11, "D3D11", "D3D11");
    EyerAVPixelFormat EyerAVPixelFormat::EYER_D3D11VA_VLD (AV_PIX_FMT_D3D11VA_VLD, AV_PIX_FMT_D3D11VA_VLD, "D3D11VA_VLD", "D3D11VA_VLD");

    EyerAVPixelFormat EyerAVPixelFormat::EYER_EXT_CVPIXELBUFFER (EYER_EXT_CVPIXELBUFFER_ID, EYER_EXT_CVPIXELBUFFER_ID, "EYER_EXT_CVPIXELBUFFER", "EXT_CVPIXELBUFFER");

    EyerAVPixelFormat::EyerAVPixelFormat()
    {
        *this = EYER_NONE;
    }

    EyerAVPixelFormat::EyerAVPixelFormat(int _id, int _ffmpegId, const EyerString & _name, const EyerString & _descName)
    {
        id          = _id;
        ffmpegId    = _ffmpegId;
        name        = _name;
        descName    = _descName;
    }

    bool EyerAVPixelFormat::operator == (const EyerAVPixelFormat & format) const
    {
        return id == format.id;
    }

    bool EyerAVPixelFormat::operator != (const EyerAVPixelFormat & format) const
    {
        return id != format.id;
    }

    EyerAVPixelFormat::EyerAVPixelFormat(const EyerAVPixelFormat & pixelFormat)
    {
        *this = pixelFormat;
    }

    EyerAVPixelFormat & EyerAVPixelFormat::operator = (const EyerAVPixelFormat & pixelFormat)
    {
        id = pixelFormat.id;
        ffmpegId = pixelFormat.ffmpegId;
        name = pixelFormat.name;
        descName = pixelFormat.descName;
        return *this;
    }

    EyerAVPixelFormat EyerAVPixelFormat::GetById(int id)
    {
        switch (id) {
            case -2: return EYER_KEEP_SAME;
            case AV_PIX_FMT_NONE: return EYER_NONE;
            case AV_PIX_FMT_YUV420P: return EYER_YUV420P;
            case AV_PIX_FMT_YUYV422: return EYER_YUYV422;
            case AV_PIX_FMT_RGB24: return EYER_RGB24;
            case AV_PIX_FMT_BGR24: return EYER_BGR24;
            case AV_PIX_FMT_YUV422P: return EYER_YUV422P;
            case AV_PIX_FMT_YUV444P: return EYER_YUV444P;
            case AV_PIX_FMT_YUV410P: return EYER_YUV410P;
            case AV_PIX_FMT_YUV411P: return EYER_YUV411P;
            case AV_PIX_FMT_GRAY8: return EYER_GRAY8;
            case AV_PIX_FMT_MONOWHITE: return EYER_MONOWHITE;
            case AV_PIX_FMT_MONOBLACK: return EYER_MONOBLACK;
            case AV_PIX_FMT_PAL8: return EYER_PAL8;
            case AV_PIX_FMT_YUVJ420P: return EYER_YUVJ420P;
            case AV_PIX_FMT_YUVJ422P: return EYER_YUVJ422P;
            case AV_PIX_FMT_YUVJ444P: return EYER_YUVJ444P;
            case AV_PIX_FMT_UYVY422: return EYER_UYVY422;
            case AV_PIX_FMT_UYYVYY411: return EYER_UYYVYY411;
            case AV_PIX_FMT_BGR8: return EYER_BGR8;
            case AV_PIX_FMT_BGR4: return EYER_BGR4;
            case AV_PIX_FMT_BGR4_BYTE: return EYER_BGR4_BYTE;
            case AV_PIX_FMT_RGB8: return EYER_RGB8;
            case AV_PIX_FMT_RGB4: return EYER_RGB4;
            case AV_PIX_FMT_RGB4_BYTE: return EYER_RGB4_BYTE;
            case AV_PIX_FMT_NV12: return EYER_NV12;
            case AV_PIX_FMT_NV21: return EYER_NV21;
            case AV_PIX_FMT_ARGB: return EYER_ARGB;
            case AV_PIX_FMT_RGBA: return EYER_RGBA;
            case AV_PIX_FMT_ABGR: return EYER_ABGR;
            case AV_PIX_FMT_BGRA: return EYER_BGRA;
            case AV_PIX_FMT_GRAY16BE: return EYER_GRAY16BE;
            case AV_PIX_FMT_GRAY16LE: return EYER_GRAY16LE;
            case AV_PIX_FMT_YUV440P: return EYER_YUV440P;
            case AV_PIX_FMT_YUVJ440P: return EYER_YUVJ440P;
            case AV_PIX_FMT_YUVA420P: return EYER_YUVA420P;
            case AV_PIX_FMT_RGB48BE: return EYER_RGB48BE;
            case AV_PIX_FMT_RGB48LE: return EYER_RGB48LE;
            case AV_PIX_FMT_RGB565BE: return EYER_RGB565BE;
            case AV_PIX_FMT_RGB565LE: return EYER_RGB565LE;
            case AV_PIX_FMT_RGB555BE: return EYER_RGB555BE;
            case AV_PIX_FMT_RGB555LE: return EYER_RGB555LE;
            case AV_PIX_FMT_BGR565BE: return EYER_BGR565BE;
            case AV_PIX_FMT_BGR565LE: return EYER_BGR565LE;
            case AV_PIX_FMT_BGR555BE: return EYER_BGR555BE;
            case AV_PIX_FMT_BGR555LE: return EYER_BGR555LE;
            case AV_PIX_FMT_YUV420P16LE: return EYER_YUV420P16LE;
            case AV_PIX_FMT_YUV420P16BE: return EYER_YUV420P16BE;
            case AV_PIX_FMT_YUV422P16LE: return EYER_YUV422P16LE;
            case AV_PIX_FMT_YUV422P16BE: return EYER_YUV422P16BE;
            case AV_PIX_FMT_YUV444P16LE: return EYER_YUV444P16LE;
            case AV_PIX_FMT_YUV444P16BE: return EYER_YUV444P16BE;
            case AV_PIX_FMT_RGB444LE: return EYER_RGB444LE;
            case AV_PIX_FMT_RGB444BE: return EYER_RGB444BE;
            case AV_PIX_FMT_BGR444LE: return EYER_BGR444LE;
            case AV_PIX_FMT_BGR444BE: return EYER_BGR444BE;
            case AV_PIX_FMT_YA8: return EYER_YA8;
            case AV_PIX_FMT_BGR48BE: return EYER_BGR48BE;
            case AV_PIX_FMT_BGR48LE: return EYER_BGR48LE;
            case AV_PIX_FMT_YUV420P9BE: return EYER_YUV420P9BE;
            case AV_PIX_FMT_YUV420P9LE: return EYER_YUV420P9LE;
            case AV_PIX_FMT_YUV420P10BE: return EYER_YUV420P10BE;
            case AV_PIX_FMT_YUV420P10LE: return EYER_YUV420P10LE;
            case AV_PIX_FMT_YUV422P10BE: return EYER_YUV422P10BE;
            case AV_PIX_FMT_YUV422P10LE: return EYER_YUV422P10LE;
            case AV_PIX_FMT_YUV444P9BE: return EYER_YUV444P9BE;
            case AV_PIX_FMT_YUV444P9LE: return EYER_YUV444P9LE;
            case AV_PIX_FMT_YUV444P10BE: return EYER_YUV444P10BE;
            case AV_PIX_FMT_YUV444P10LE: return EYER_YUV444P10LE;
            case AV_PIX_FMT_YUV422P9BE: return EYER_YUV422P9BE;
            case AV_PIX_FMT_YUV422P9LE: return EYER_YUV422P9LE;
            case AV_PIX_FMT_GBRP: return EYER_GBRP;
            case AV_PIX_FMT_GBRP9BE: return EYER_GBRP9BE;
            case AV_PIX_FMT_GBRP9LE: return EYER_GBRP9LE;
            case AV_PIX_FMT_GBRP10BE: return EYER_GBRP10BE;
            case AV_PIX_FMT_GBRP10LE: return EYER_GBRP10LE;
            case AV_PIX_FMT_GBRP16BE: return EYER_GBRP16BE;
            case AV_PIX_FMT_GBRP16LE: return EYER_GBRP16LE;
            case AV_PIX_FMT_YUVA422P: return EYER_YUVA422P;
            case AV_PIX_FMT_YUVA444P: return EYER_YUVA444P;
            case AV_PIX_FMT_YUVA420P9BE: return EYER_YUVA420P9BE;
            case AV_PIX_FMT_YUVA420P9LE: return EYER_YUVA420P9LE;
            case AV_PIX_FMT_YUVA422P9BE: return EYER_YUVA422P9BE;
            case AV_PIX_FMT_YUVA422P9LE: return EYER_YUVA422P9LE;
            case AV_PIX_FMT_YUVA444P9BE: return EYER_YUVA444P9BE;
            case AV_PIX_FMT_YUVA444P9LE: return EYER_YUVA444P9LE;
            case AV_PIX_FMT_YUVA420P10BE: return EYER_YUVA420P10BE;
            case AV_PIX_FMT_YUVA420P10LE: return EYER_YUVA420P10LE;
            case AV_PIX_FMT_YUVA422P10BE: return EYER_YUVA422P10BE;
            case AV_PIX_FMT_YUVA422P10LE: return EYER_YUVA422P10LE;
            case AV_PIX_FMT_YUVA444P10BE: return EYER_YUVA444P10BE;
            case AV_PIX_FMT_YUVA444P10LE: return EYER_YUVA444P10LE;
            case AV_PIX_FMT_YUVA420P16BE: return EYER_YUVA420P16BE;
            case AV_PIX_FMT_YUVA420P16LE: return EYER_YUVA420P16LE;
            case AV_PIX_FMT_YUVA422P16BE: return EYER_YUVA422P16BE;
            case AV_PIX_FMT_YUVA422P16LE: return EYER_YUVA422P16LE;
            case AV_PIX_FMT_YUVA444P16BE: return EYER_YUVA444P16BE;
            case AV_PIX_FMT_YUVA444P16LE: return EYER_YUVA444P16LE;
            case AV_PIX_FMT_XYZ12LE: return EYER_XYZ12LE;
            case AV_PIX_FMT_XYZ12BE: return EYER_XYZ12BE;
            case AV_PIX_FMT_NV16: return EYER_NV16;
            case AV_PIX_FMT_NV20LE: return EYER_NV20LE;
            case AV_PIX_FMT_NV20BE: return EYER_NV20BE;
            case AV_PIX_FMT_RGBA64BE: return EYER_RGBA64BE;
            case AV_PIX_FMT_RGBA64LE: return EYER_RGBA64LE;
            case AV_PIX_FMT_BGRA64BE: return EYER_BGRA64BE;
            case AV_PIX_FMT_BGRA64LE: return EYER_BGRA64LE;
            case AV_PIX_FMT_YVYU422: return EYER_YVYU422;
            case AV_PIX_FMT_YA16BE: return EYER_YA16BE;
            case AV_PIX_FMT_YA16LE: return EYER_YA16LE;
            case AV_PIX_FMT_GBRAP: return EYER_GBRAP;
            case AV_PIX_FMT_GBRAP16BE: return EYER_GBRAP16BE;
            case AV_PIX_FMT_GBRAP16LE: return EYER_GBRAP16LE;
            case AV_PIX_FMT_0RGB: return EYER_0RGB;
            case AV_PIX_FMT_RGB0: return EYER_RGB0;
            case AV_PIX_FMT_0BGR: return EYER_0BGR;
            case AV_PIX_FMT_BGR0: return EYER_BGR0;
            case AV_PIX_FMT_YUV420P12BE: return EYER_YUV420P12BE;
            case AV_PIX_FMT_YUV420P12LE: return EYER_YUV420P12LE;
            case AV_PIX_FMT_YUV420P14BE: return EYER_YUV420P14BE;
            case AV_PIX_FMT_YUV420P14LE: return EYER_YUV420P14LE;
            case AV_PIX_FMT_YUV422P12BE: return EYER_YUV422P12BE;
            case AV_PIX_FMT_YUV422P12LE: return EYER_YUV422P12LE;
            case AV_PIX_FMT_YUV422P14BE: return EYER_YUV422P14BE;
            case AV_PIX_FMT_YUV422P14LE: return EYER_YUV422P14LE;
            case AV_PIX_FMT_YUV444P12BE: return EYER_YUV444P12BE;
            case AV_PIX_FMT_YUV444P12LE: return EYER_YUV444P12LE;
            case AV_PIX_FMT_YUV444P14BE: return EYER_YUV444P14BE;
            case AV_PIX_FMT_YUV444P14LE: return EYER_YUV444P14LE;
            case AV_PIX_FMT_GBRP12BE: return EYER_GBRP12BE;
            case AV_PIX_FMT_GBRP12LE: return EYER_GBRP12LE;
            case AV_PIX_FMT_GBRP14BE: return EYER_GBRP14BE;
            case AV_PIX_FMT_GBRP14LE: return EYER_GBRP14LE;
            case AV_PIX_FMT_YUVJ411P: return EYER_YUVJ411P;
            case AV_PIX_FMT_BAYER_BGGR8: return EYER_BAYER_BGGR8;
            case AV_PIX_FMT_BAYER_RGGB8: return EYER_BAYER_RGGB8;
            case AV_PIX_FMT_BAYER_GBRG8: return EYER_BAYER_GBRG8;
            case AV_PIX_FMT_BAYER_GRBG8: return EYER_BAYER_GRBG8;
            case AV_PIX_FMT_BAYER_BGGR16LE: return EYER_BAYER_BGGR16LE;
            case AV_PIX_FMT_BAYER_BGGR16BE: return EYER_BAYER_BGGR16BE;
            case AV_PIX_FMT_BAYER_RGGB16LE: return EYER_BAYER_RGGB16LE;
            case AV_PIX_FMT_BAYER_RGGB16BE: return EYER_BAYER_RGGB16BE;
            case AV_PIX_FMT_BAYER_GBRG16LE: return EYER_BAYER_GBRG16LE;
            case AV_PIX_FMT_BAYER_GBRG16BE: return EYER_BAYER_GBRG16BE;
            case AV_PIX_FMT_BAYER_GRBG16LE: return EYER_BAYER_GRBG16LE;
            case AV_PIX_FMT_BAYER_GRBG16BE: return EYER_BAYER_GRBG16BE;
            case AV_PIX_FMT_YUV440P10LE: return EYER_YUV440P10LE;
            case AV_PIX_FMT_YUV440P10BE: return EYER_YUV440P10BE;
            case AV_PIX_FMT_YUV440P12LE: return EYER_YUV440P12LE;
            case AV_PIX_FMT_YUV440P12BE: return EYER_YUV440P12BE;
            case AV_PIX_FMT_AYUV64LE: return EYER_AYUV64LE;
            case AV_PIX_FMT_AYUV64BE: return EYER_AYUV64BE;
            case AV_PIX_FMT_P010LE: return EYER_P010LE;
            case AV_PIX_FMT_P010BE: return EYER_P010BE;
            case AV_PIX_FMT_GBRAP12BE: return EYER_GBRAP12BE;
            case AV_PIX_FMT_GBRAP12LE: return EYER_GBRAP12LE;
            case AV_PIX_FMT_GBRAP10BE: return EYER_GBRAP10BE;
            case AV_PIX_FMT_GBRAP10LE: return EYER_GBRAP10LE;
            case AV_PIX_FMT_GRAY12BE: return EYER_GRAY12BE;
            case AV_PIX_FMT_GRAY12LE: return EYER_GRAY12LE;
            case AV_PIX_FMT_GRAY10BE: return EYER_GRAY10BE;
            case AV_PIX_FMT_GRAY10LE: return EYER_GRAY10LE;
            case AV_PIX_FMT_P016LE: return EYER_P016LE;
            case AV_PIX_FMT_P016BE: return EYER_P016BE;
            case AV_PIX_FMT_GRAY9BE: return EYER_GRAY9BE;
            case AV_PIX_FMT_GRAY9LE: return EYER_GRAY9LE;
            case AV_PIX_FMT_GBRPF32BE: return EYER_GBRPF32BE;
            case AV_PIX_FMT_GBRPF32LE: return EYER_GBRPF32LE;
            case AV_PIX_FMT_GBRAPF32BE: return EYER_GBRAPF32BE;
            case AV_PIX_FMT_GBRAPF32LE: return EYER_GBRAPF32LE;
            case AV_PIX_FMT_GRAY14BE: return EYER_GRAY14BE;
            case AV_PIX_FMT_GRAY14LE: return EYER_GRAY14LE;
            case AV_PIX_FMT_GRAYF32BE: return EYER_GRAYF32BE;
            case AV_PIX_FMT_GRAYF32LE: return EYER_GRAYF32LE;
            case AV_PIX_FMT_YUVA422P12BE: return EYER_YUVA422P12BE;
            case AV_PIX_FMT_YUVA422P12LE: return EYER_YUVA422P12LE;
            case AV_PIX_FMT_YUVA444P12BE: return EYER_YUVA444P12BE;
            case AV_PIX_FMT_YUVA444P12LE: return EYER_YUVA444P12LE;
            case AV_PIX_FMT_NV24: return EYER_NV24;
            case AV_PIX_FMT_NV42: return EYER_NV42;
            case AV_PIX_FMT_Y210BE: return EYER_Y210BE;
            case AV_PIX_FMT_Y210LE: return EYER_Y210LE;
            case AV_PIX_FMT_X2RGB10LE: return EYER_X2RGB10LE;
            case AV_PIX_FMT_X2RGB10BE: return EYER_X2RGB10BE;

            case EYER_EXT_CVPIXELBUFFER_ID: return EYER_EXT_CVPIXELBUFFER;
        }

        return EYER_NONE;
    }

    EyerAVPixelFormat EyerAVPixelFormat::GetByFFmpegId(int ffmpegId)
    {
        switch (ffmpegId) {
            case -2: return EYER_KEEP_SAME;
            case AV_PIX_FMT_NONE: return EYER_NONE;
            case AV_PIX_FMT_YUV420P: return EYER_YUV420P;
            case AV_PIX_FMT_YUYV422: return EYER_YUYV422;
            case AV_PIX_FMT_RGB24: return EYER_RGB24;
            case AV_PIX_FMT_BGR24: return EYER_BGR24;
            case AV_PIX_FMT_YUV422P: return EYER_YUV422P;
            case AV_PIX_FMT_YUV444P: return EYER_YUV444P;
            case AV_PIX_FMT_YUV410P: return EYER_YUV410P;
            case AV_PIX_FMT_YUV411P: return EYER_YUV411P;
            case AV_PIX_FMT_GRAY8: return EYER_GRAY8;
            case AV_PIX_FMT_MONOWHITE: return EYER_MONOWHITE;
            case AV_PIX_FMT_MONOBLACK: return EYER_MONOBLACK;
            case AV_PIX_FMT_PAL8: return EYER_PAL8;
            case AV_PIX_FMT_YUVJ420P: return EYER_YUVJ420P;
            case AV_PIX_FMT_YUVJ422P: return EYER_YUVJ422P;
            case AV_PIX_FMT_YUVJ444P: return EYER_YUVJ444P;
            case AV_PIX_FMT_UYVY422: return EYER_UYVY422;
            case AV_PIX_FMT_UYYVYY411: return EYER_UYYVYY411;
            case AV_PIX_FMT_BGR8: return EYER_BGR8;
            case AV_PIX_FMT_BGR4: return EYER_BGR4;
            case AV_PIX_FMT_BGR4_BYTE: return EYER_BGR4_BYTE;
            case AV_PIX_FMT_RGB8: return EYER_RGB8;
            case AV_PIX_FMT_RGB4: return EYER_RGB4;
            case AV_PIX_FMT_RGB4_BYTE: return EYER_RGB4_BYTE;
            case AV_PIX_FMT_NV12: return EYER_NV12;
            case AV_PIX_FMT_NV21: return EYER_NV21;
            case AV_PIX_FMT_ARGB: return EYER_ARGB;
            case AV_PIX_FMT_RGBA: return EYER_RGBA;
            case AV_PIX_FMT_ABGR: return EYER_ABGR;
            case AV_PIX_FMT_BGRA: return EYER_BGRA;
            case AV_PIX_FMT_GRAY16BE: return EYER_GRAY16BE;
            case AV_PIX_FMT_GRAY16LE: return EYER_GRAY16LE;
            case AV_PIX_FMT_YUV440P: return EYER_YUV440P;
            case AV_PIX_FMT_YUVJ440P: return EYER_YUVJ440P;
            case AV_PIX_FMT_YUVA420P: return EYER_YUVA420P;
            case AV_PIX_FMT_RGB48BE: return EYER_RGB48BE;
            case AV_PIX_FMT_RGB48LE: return EYER_RGB48LE;
            case AV_PIX_FMT_RGB565BE: return EYER_RGB565BE;
            case AV_PIX_FMT_RGB565LE: return EYER_RGB565LE;
            case AV_PIX_FMT_RGB555BE: return EYER_RGB555BE;
            case AV_PIX_FMT_RGB555LE: return EYER_RGB555LE;
            case AV_PIX_FMT_BGR565BE: return EYER_BGR565BE;
            case AV_PIX_FMT_BGR565LE: return EYER_BGR565LE;
            case AV_PIX_FMT_BGR555BE: return EYER_BGR555BE;
            case AV_PIX_FMT_BGR555LE: return EYER_BGR555LE;
            case AV_PIX_FMT_YUV420P16LE: return EYER_YUV420P16LE;
            case AV_PIX_FMT_YUV420P16BE: return EYER_YUV420P16BE;
            case AV_PIX_FMT_YUV422P16LE: return EYER_YUV422P16LE;
            case AV_PIX_FMT_YUV422P16BE: return EYER_YUV422P16BE;
            case AV_PIX_FMT_YUV444P16LE: return EYER_YUV444P16LE;
            case AV_PIX_FMT_YUV444P16BE: return EYER_YUV444P16BE;
            case AV_PIX_FMT_RGB444LE: return EYER_RGB444LE;
            case AV_PIX_FMT_RGB444BE: return EYER_RGB444BE;
            case AV_PIX_FMT_BGR444LE: return EYER_BGR444LE;
            case AV_PIX_FMT_BGR444BE: return EYER_BGR444BE;
            case AV_PIX_FMT_YA8: return EYER_YA8;
            case AV_PIX_FMT_BGR48BE: return EYER_BGR48BE;
            case AV_PIX_FMT_BGR48LE: return EYER_BGR48LE;
            case AV_PIX_FMT_YUV420P9BE: return EYER_YUV420P9BE;
            case AV_PIX_FMT_YUV420P9LE: return EYER_YUV420P9LE;
            case AV_PIX_FMT_YUV420P10BE: return EYER_YUV420P10BE;
            case AV_PIX_FMT_YUV420P10LE: return EYER_YUV420P10LE;
            case AV_PIX_FMT_YUV422P10BE: return EYER_YUV422P10BE;
            case AV_PIX_FMT_YUV422P10LE: return EYER_YUV422P10LE;
            case AV_PIX_FMT_YUV444P9BE: return EYER_YUV444P9BE;
            case AV_PIX_FMT_YUV444P9LE: return EYER_YUV444P9LE;
            case AV_PIX_FMT_YUV444P10BE: return EYER_YUV444P10BE;
            case AV_PIX_FMT_YUV444P10LE: return EYER_YUV444P10LE;
            case AV_PIX_FMT_YUV422P9BE: return EYER_YUV422P9BE;
            case AV_PIX_FMT_YUV422P9LE: return EYER_YUV422P9LE;
            case AV_PIX_FMT_GBRP: return EYER_GBRP;
            case AV_PIX_FMT_GBRP9BE: return EYER_GBRP9BE;
            case AV_PIX_FMT_GBRP9LE: return EYER_GBRP9LE;
            case AV_PIX_FMT_GBRP10BE: return EYER_GBRP10BE;
            case AV_PIX_FMT_GBRP10LE: return EYER_GBRP10LE;
            case AV_PIX_FMT_GBRP16BE: return EYER_GBRP16BE;
            case AV_PIX_FMT_GBRP16LE: return EYER_GBRP16LE;
            case AV_PIX_FMT_YUVA422P: return EYER_YUVA422P;
            case AV_PIX_FMT_YUVA444P: return EYER_YUVA444P;
            case AV_PIX_FMT_YUVA420P9BE: return EYER_YUVA420P9BE;
            case AV_PIX_FMT_YUVA420P9LE: return EYER_YUVA420P9LE;
            case AV_PIX_FMT_YUVA422P9BE: return EYER_YUVA422P9BE;
            case AV_PIX_FMT_YUVA422P9LE: return EYER_YUVA422P9LE;
            case AV_PIX_FMT_YUVA444P9BE: return EYER_YUVA444P9BE;
            case AV_PIX_FMT_YUVA444P9LE: return EYER_YUVA444P9LE;
            case AV_PIX_FMT_YUVA420P10BE: return EYER_YUVA420P10BE;
            case AV_PIX_FMT_YUVA420P10LE: return EYER_YUVA420P10LE;
            case AV_PIX_FMT_YUVA422P10BE: return EYER_YUVA422P10BE;
            case AV_PIX_FMT_YUVA422P10LE: return EYER_YUVA422P10LE;
            case AV_PIX_FMT_YUVA444P10BE: return EYER_YUVA444P10BE;
            case AV_PIX_FMT_YUVA444P10LE: return EYER_YUVA444P10LE;
            case AV_PIX_FMT_YUVA420P16BE: return EYER_YUVA420P16BE;
            case AV_PIX_FMT_YUVA420P16LE: return EYER_YUVA420P16LE;
            case AV_PIX_FMT_YUVA422P16BE: return EYER_YUVA422P16BE;
            case AV_PIX_FMT_YUVA422P16LE: return EYER_YUVA422P16LE;
            case AV_PIX_FMT_YUVA444P16BE: return EYER_YUVA444P16BE;
            case AV_PIX_FMT_YUVA444P16LE: return EYER_YUVA444P16LE;
            case AV_PIX_FMT_XYZ12LE: return EYER_XYZ12LE;
            case AV_PIX_FMT_XYZ12BE: return EYER_XYZ12BE;
            case AV_PIX_FMT_NV16: return EYER_NV16;
            case AV_PIX_FMT_NV20LE: return EYER_NV20LE;
            case AV_PIX_FMT_NV20BE: return EYER_NV20BE;
            case AV_PIX_FMT_RGBA64BE: return EYER_RGBA64BE;
            case AV_PIX_FMT_RGBA64LE: return EYER_RGBA64LE;
            case AV_PIX_FMT_BGRA64BE: return EYER_BGRA64BE;
            case AV_PIX_FMT_BGRA64LE: return EYER_BGRA64LE;
            case AV_PIX_FMT_YVYU422: return EYER_YVYU422;
            case AV_PIX_FMT_YA16BE: return EYER_YA16BE;
            case AV_PIX_FMT_YA16LE: return EYER_YA16LE;
            case AV_PIX_FMT_GBRAP: return EYER_GBRAP;
            case AV_PIX_FMT_GBRAP16BE: return EYER_GBRAP16BE;
            case AV_PIX_FMT_GBRAP16LE: return EYER_GBRAP16LE;
            case AV_PIX_FMT_0RGB: return EYER_0RGB;
            case AV_PIX_FMT_RGB0: return EYER_RGB0;
            case AV_PIX_FMT_0BGR: return EYER_0BGR;
            case AV_PIX_FMT_BGR0: return EYER_BGR0;
            case AV_PIX_FMT_YUV420P12BE: return EYER_YUV420P12BE;
            case AV_PIX_FMT_YUV420P12LE: return EYER_YUV420P12LE;
            case AV_PIX_FMT_YUV420P14BE: return EYER_YUV420P14BE;
            case AV_PIX_FMT_YUV420P14LE: return EYER_YUV420P14LE;
            case AV_PIX_FMT_YUV422P12BE: return EYER_YUV422P12BE;
            case AV_PIX_FMT_YUV422P12LE: return EYER_YUV422P12LE;
            case AV_PIX_FMT_YUV422P14BE: return EYER_YUV422P14BE;
            case AV_PIX_FMT_YUV422P14LE: return EYER_YUV422P14LE;
            case AV_PIX_FMT_YUV444P12BE: return EYER_YUV444P12BE;
            case AV_PIX_FMT_YUV444P12LE: return EYER_YUV444P12LE;
            case AV_PIX_FMT_YUV444P14BE: return EYER_YUV444P14BE;
            case AV_PIX_FMT_YUV444P14LE: return EYER_YUV444P14LE;
            case AV_PIX_FMT_GBRP12BE: return EYER_GBRP12BE;
            case AV_PIX_FMT_GBRP12LE: return EYER_GBRP12LE;
            case AV_PIX_FMT_GBRP14BE: return EYER_GBRP14BE;
            case AV_PIX_FMT_GBRP14LE: return EYER_GBRP14LE;
            case AV_PIX_FMT_YUVJ411P: return EYER_YUVJ411P;
            case AV_PIX_FMT_BAYER_BGGR8: return EYER_BAYER_BGGR8;
            case AV_PIX_FMT_BAYER_RGGB8: return EYER_BAYER_RGGB8;
            case AV_PIX_FMT_BAYER_GBRG8: return EYER_BAYER_GBRG8;
            case AV_PIX_FMT_BAYER_GRBG8: return EYER_BAYER_GRBG8;
            case AV_PIX_FMT_BAYER_BGGR16LE: return EYER_BAYER_BGGR16LE;
            case AV_PIX_FMT_BAYER_BGGR16BE: return EYER_BAYER_BGGR16BE;
            case AV_PIX_FMT_BAYER_RGGB16LE: return EYER_BAYER_RGGB16LE;
            case AV_PIX_FMT_BAYER_RGGB16BE: return EYER_BAYER_RGGB16BE;
            case AV_PIX_FMT_BAYER_GBRG16LE: return EYER_BAYER_GBRG16LE;
            case AV_PIX_FMT_BAYER_GBRG16BE: return EYER_BAYER_GBRG16BE;
            case AV_PIX_FMT_BAYER_GRBG16LE: return EYER_BAYER_GRBG16LE;
            case AV_PIX_FMT_BAYER_GRBG16BE: return EYER_BAYER_GRBG16BE;
            case AV_PIX_FMT_YUV440P10LE: return EYER_YUV440P10LE;
            case AV_PIX_FMT_YUV440P10BE: return EYER_YUV440P10BE;
            case AV_PIX_FMT_YUV440P12LE: return EYER_YUV440P12LE;
            case AV_PIX_FMT_YUV440P12BE: return EYER_YUV440P12BE;
            case AV_PIX_FMT_AYUV64LE: return EYER_AYUV64LE;
            case AV_PIX_FMT_AYUV64BE: return EYER_AYUV64BE;
            case AV_PIX_FMT_P010LE: return EYER_P010LE;
            case AV_PIX_FMT_P010BE: return EYER_P010BE;
            case AV_PIX_FMT_GBRAP12BE: return EYER_GBRAP12BE;
            case AV_PIX_FMT_GBRAP12LE: return EYER_GBRAP12LE;
            case AV_PIX_FMT_GBRAP10BE: return EYER_GBRAP10BE;
            case AV_PIX_FMT_GBRAP10LE: return EYER_GBRAP10LE;
            case AV_PIX_FMT_GRAY12BE: return EYER_GRAY12BE;
            case AV_PIX_FMT_GRAY12LE: return EYER_GRAY12LE;
            case AV_PIX_FMT_GRAY10BE: return EYER_GRAY10BE;
            case AV_PIX_FMT_GRAY10LE: return EYER_GRAY10LE;
            case AV_PIX_FMT_P016LE: return EYER_P016LE;
            case AV_PIX_FMT_P016BE: return EYER_P016BE;
            case AV_PIX_FMT_GRAY9BE: return EYER_GRAY9BE;
            case AV_PIX_FMT_GRAY9LE: return EYER_GRAY9LE;
            case AV_PIX_FMT_GBRPF32BE: return EYER_GBRPF32BE;
            case AV_PIX_FMT_GBRPF32LE: return EYER_GBRPF32LE;
            case AV_PIX_FMT_GBRAPF32BE: return EYER_GBRAPF32BE;
            case AV_PIX_FMT_GBRAPF32LE: return EYER_GBRAPF32LE;
            case AV_PIX_FMT_GRAY14BE: return EYER_GRAY14BE;
            case AV_PIX_FMT_GRAY14LE: return EYER_GRAY14LE;
            case AV_PIX_FMT_GRAYF32BE: return EYER_GRAYF32BE;
            case AV_PIX_FMT_GRAYF32LE: return EYER_GRAYF32LE;
            case AV_PIX_FMT_YUVA422P12BE: return EYER_YUVA422P12BE;
            case AV_PIX_FMT_YUVA422P12LE: return EYER_YUVA422P12LE;
            case AV_PIX_FMT_YUVA444P12BE: return EYER_YUVA444P12BE;
            case AV_PIX_FMT_YUVA444P12LE: return EYER_YUVA444P12LE;
            case AV_PIX_FMT_NV24: return EYER_NV24;
            case AV_PIX_FMT_NV42: return EYER_NV42;
            case AV_PIX_FMT_Y210BE: return EYER_Y210BE;
            case AV_PIX_FMT_Y210LE: return EYER_Y210LE;
            case AV_PIX_FMT_X2RGB10LE: return EYER_X2RGB10LE;
            case AV_PIX_FMT_X2RGB10BE: return EYER_X2RGB10BE;


            case AV_PIX_FMT_D3D11: return EYER_D3D11;
            case AV_PIX_FMT_D3D11VA_VLD: return EYER_D3D11VA_VLD;

            case EYER_EXT_CVPIXELBUFFER_ID: return EYER_EXT_CVPIXELBUFFER;
        }

        return EYER_NONE;
    }

    const int EyerAVPixelFormat::GetId() const
    {
        return id;
    }

    const int EyerAVPixelFormat::GetFFmpegId() const
    {
        return ffmpegId;
    }

    const EyerString EyerAVPixelFormat::GetName() const
    {
        return name;
    }

    const EyerString EyerAVPixelFormat::GetDescName() const
    {
        return descName;
    }

    const int EyerAVPixelFormat::GetPixelBitDepth(int index) const
    {
        const AVPixFmtDescriptor * pixFmtDescriptor = av_pix_fmt_desc_get((AVPixelFormat)ffmpegId);
        return pixFmtDescriptor->comp[index].depth;
    }

    const int EyerAVPixelFormat::GetPixelLog2ChromaW() const
    {
        const AVPixFmtDescriptor * pixFmtDescriptor = av_pix_fmt_desc_get((AVPixelFormat)ffmpegId);
        return pixFmtDescriptor->log2_chroma_w;
    }

    const int EyerAVPixelFormat::GetPixelLog2ChromaH() const
    {
        const AVPixFmtDescriptor * pixFmtDescriptor = av_pix_fmt_desc_get((AVPixelFormat)ffmpegId);
        return pixFmtDescriptor->log2_chroma_h;
    }
}