#ifndef EYERLIB_EYERAVERRORCODE_HPP
#define EYERLIB_EYERAVERRORCODE_HPP

#define EYER_AV_OK                                  0
#define EYER_AV_DECODER_LINE_PTS_ERROR              -1
#define EYER_AV_DECODER_LINE_NOT_FIND               -2
#define EYER_AV_DECODER_LINE_NOT_MATCH_REGION       -3
#define EYER_AV_DECODER_LINE_NEED_MORE_DATA         -4
#define EYER_AV_DECODER_LINE_DECODER_ERROR          -5
#define EYER_AV_DECODER_LINE_DECODER_END_OF_FILE    -6

#endif //EYERLIB_EYERAVERRORCODE_HPP
